package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"strconv"
	"strings"

	"github.com/adhocteam/pushup/internal/ast"
	"github.com/adhocteam/pushup/internal/source"
	"github.com/adhocteam/pushup/internal/up"
	"github.com/adhocteam/pushup/internal/version"
)

type Generator interface {
	Generate(*up.CompileUnit) ([]byte, error)
}

type generateFunc func(*up.CompileUnit) ([]byte, error)

func (f generateFunc) Generate(unit *up.CompileUnit) ([]byte, error) {
	return f(unit)
}

type generator struct {
	unit    *up.CompileUnit
	imports map[string]string
	content sections
}

type sections struct {
	comments bytes.Buffer
	imports  bytes.Buffer
	code     bytes.Buffer
}

func (s *sections) reset() {
	(&s.comments).Reset()
	(&s.imports).Reset()
	(&s.code).Reset()
}

func New() *generator {
	g := &generator{}
	g.reset()
	return g
}

const (
	methodReceiverName = "up"
	ioWriterVar        = "__pushup_b"
	pushupApi          = "github.com/adhocteam/pushup"
	pushupModulePath   = "github.com/adhocteam/pushup"
)

func (g *generator) reset() {
	g.content.reset()
	g.imports = make(map[string]string)
}

func (g *generator) Generate(unit *up.CompileUnit) ([]byte, error) {
	g.unit = unit
	g.reset()

	g.addComment("Code generated by Pushup; DO NOT EDIT")
	g.addComment("Version: " + version.Version())

	g.generateResponder(unit.TypeName, unit.Handler, g.generate)

	type route struct {
		path     string
		typeName string
	}
	var routes []route

	routes = append(routes, route{path: unit.Route, typeName: unit.TypeName})

	for _, partial := range g.unit.Partials {
		g.generateResponder(partial.TypeName, unit.Handler, func() {
			// FIXME(paulsmith): need to generate code for everything but emitting
			// top-level page values to the output
			g.genNodePartial(g.unit.Nodes, partial)
		})
		routes = append(routes, route{path: partial.Route, typeName: partial.TypeName})
	}

	// Register routes
	g.println("")
	g.println("func init() {")
	g.addImport(pushupModulePath+"/route", "")
	for _, route := range routes {
		g.printf("route.Register(\"%s\", new(%s))\n", route.path, route.typeName)
	}
	g.println("}")

	raw, err := g.bytes()
	if err != nil {
		return nil, fmt.Errorf("getting generated code bytes: %w", err)
	}

	code, err := format.Source(raw)
	if err != nil {
		return nil, fmt.Errorf("formatting generated Go code: %w", err)
	}

	return code, nil
}

func (g *generator) generateResponder(typename string, handler *ast.NodeGoCode, codegenFn func()) {
	g.printf("type %s struct {", typename)
	g.println("}")

	g.addImport("net/http", "")
	g.printf("func (%s *%s) Respond(w http.ResponseWriter, req *http.Request) error {\n", methodReceiverName, typename)
	g.println("w.Header().Set(\"Content-Type\", \"text/html\")")

	if handler != nil {
		srcLineNo := g.lineNo(handler.Pos())
		lines := strings.Split(handler.Code, "\n")
		for _, line := range lines {
			g.emitLineDirective(srcLineNo)
			g.println(line)
			srcLineNo++
		}
	}

	g.println("// Begin user Go code and HTML")
	g.println("{")

	g.addImport("bytes", "")
	g.printf("%s := new(bytes.Buffer)\n", ioWriterVar)
	codegenFn()
	g.println("io.Copy(w, __pushup_b)")

	g.println("}")
	g.println("// End user Go code and HTML")

	g.println("return nil")
	g.println("}") // end Respond() method
}

func (g *generator) generate() {
	ops := g.collectOutputOps(g.unit.Nodes)
	g.generateFromOps(ops)
}

func (g *generator) generateFromOps(ops []outputOp) {
	g.addImport("io", "")

	for _, op := range ops {
		g.emitLineDirective(g.lineNo(op.span))

		switch op.kind {
		case opStatic:
			g.printf("io.WriteString(%s, %s)\n", ioWriterVar, strconv.Quote(op.content))
		case opDynamic:
			g.addImport(pushupApi, "api")
			g.printf("api.PrintEscaped(%s, %s)\n", ioWriterVar, op.expr)
		case opFlush:
			// TODO: ensure buffered content is written
			continue
		case opGoCode:
			g.println(op.content)
		case opControlStart:
			g.printf("%s {\n", op.content)
		case opControlElse:
			g.println("} else {")
		case opControlEnd:
			g.println("}")
		default:
			panic("unknown output op kind")
		}
	}
}

func (g *generator) collectOutputOps(node ast.Node) []outputOp {
	collector := new(outputCollector)
	g.gatherOutputOps(node, collector)
	return collector.optimize()
}

func (g *generator) gatherOutputOps(node ast.Node, collector *outputCollector) {
	switch n := node.(type) {
	case *ast.NodeLiteral:
		collector.add(outputOp{
			kind:    opStatic,
			content: n.Text,
			span:    n.Span,
		})

	case *ast.NodeElement:
		collector.add(outputOp{
			kind:    opStatic,
			content: n.Tag.Start(),
			span:    n.Span,
		})

		g.gatherOutputOps(n.Children, collector)

		collector.add(outputOp{
			kind:    opStatic,
			content: n.Tag.End(),
			span:    n.Span,
		})

	case *ast.NodeGoStrExpr:
		collector.add(outputOp{
			kind: opDynamic,
			expr: n.Expr,
			span: n.Span,
		})

	case *ast.NodeIf:
		collector.add(outputOp{kind: opFlush})
		collector.add(outputOp{
			kind:    opControlStart,
			content: "if " + n.Cond.Expr,
			span:    n.Pos(),
		})
		g.gatherOutputOps(n.Then, collector)
		if n.Alt != nil {
			collector.add(outputOp{
				kind: opControlElse,
				span: n.Alt.Pos(),
			})
			g.gatherOutputOps(n.Alt, collector)
		}
		collector.add(outputOp{
			kind: opControlEnd,
			span: n.Then.Pos(), // FIXME??
		})
		collector.add(outputOp{kind: opFlush})

	case *ast.NodeFor:
		collector.add(outputOp{kind: opFlush})
		collector.add(outputOp{
			kind:    opControlStart,
			content: "for " + n.Clause.Code,
			span:    n.Pos(),
		})
		g.gatherOutputOps(n.Block, collector)
		collector.add(outputOp{
			kind: opControlEnd,
			span: n.Block.Pos(), // FIXME??
		})
		collector.add(outputOp{kind: opFlush})

	case *ast.NodeList:
		for child := range n.All() {
			g.gatherOutputOps(child, collector)
		}

	case *ast.NodeGoCode:
		if n.Context == ast.InlineGoCode {
			collector.add(outputOp{kind: opFlush})
			collector.add(outputOp{
				kind:    opGoCode,
				content: n.Code,
				span:    n.Span,
			})
			collector.add(outputOp{kind: opFlush})
		}

	case *ast.NodePartial:
		g.gatherOutputOps(n.Block, collector)

	default:
		panic(fmt.Sprintf("unexpected node type: %T %v", n, n))
	}
}

func (g *generator) nodeLineNo(e ast.Node) {
	g.emitLineDirective(g.lineNo(e.Pos()))
}

// NOTE(paulsmith): per DOM spec, "In tree order is preorder, depth-first traversal of a tree."

func (g *generator) genNodePartial(n ast.Node, p *up.Partial) {
	var f ast.Inspector
	var state int
	const (
		stateStart int = iota
		stateInPartialScope
	)
	state = stateStart
	nodes := &ast.NodeList{}

	f = func(n ast.Node) bool {
		if n != nil {
			switch n := n.(type) {
			case *ast.NodePartial:
				if n == p.Node {
					state = stateInPartialScope
				}
				f(n.Block)
				state = stateStart
				return false
			case *ast.NodeList:
				if state == stateInPartialScope {
					nodes.AppendFromList(n)
				} else {
					for node := range n.All() {
						f(node)
					}
				}
			case *ast.NodeLiteral:
				if state == stateInPartialScope {
					g.addImport("io", "")
					g.nodeLineNo(n)
					g.printf("io.WriteString(%s, %s)\n", ioWriterVar, strconv.Quote(n.Text))
				}
			default:
				if state == stateInPartialScope {
					nodes.Append(n)
				}
			}
		}

		return false
	}

	ast.Inspect(n, f)

	ops := g.collectOutputOps(nodes)
	g.generateFromOps(ops)
}

func (g *generator) genElement(e *ast.NodeElement, f ast.Inspector) {
	g.addImport("io", "")
	g.nodeLineNo(e)
	f(e.StartTagNodes)
	f(e.Children)
	g.printf("io.WriteString(%s, %s)\n", ioWriterVar, strconv.Quote(e.Tag.End()))
}

func (g *generator) addComment(comment string) {
	fmt.Fprintln(&g.content.comments, "//", comment)
}

func (g *generator) addImport(path, pkgName string) {
	g.imports[path] = pkgName
}

func (g *generator) println(code string) {
	fmt.Fprintln(&g.content.code, code)
}

func (g *generator) printf(format string, a ...any) {
	fmt.Fprintf(&g.content.code, format, a...)
}

func (g *generator) lineNo(s source.Span) int {
	return lineCount(g.unit.File.Content[:s.Start+1])
}

func (g *generator) emitLineDirective(n int) {
	fmt.Fprintf(&g.content.code, "//line %s:%d\n", g.unit.File.Path, n)
}

func (g *generator) bytes() ([]byte, error) {
	pkgDecl := strings.NewReader("package " + g.unit.Package + "\n")

	if len(g.imports) > 0 {
		fmt.Fprintln(&g.content.imports, "import (")
		for path, pkgName := range g.imports {
			if pkgName == "" {
				fmt.Fprintf(&g.content.imports, "\t%q\n", path)
			} else {
				fmt.Fprintf(&g.content.imports, "\t%s %q\n", pkgName, path)
			}
		}
		fmt.Fprintln(&g.content.imports, ")")
	}

	bufs := []io.Reader{
		&g.content.comments,
		pkgDecl,
		&g.content.imports,
		&g.content.code,
	}
	return io.ReadAll(io.MultiReader(bufs...))
}

var nl = []byte{'\n'}

func lineCount(s []byte) int {
	return bytes.Count(s, nl) + 1
}
