package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"strconv"
	"strings"

	"github.com/adhocteam/pushup/internal/ast"
	"github.com/adhocteam/pushup/internal/source"
	"github.com/adhocteam/pushup/internal/up"
	"github.com/adhocteam/pushup/internal/version"
)

type Generator interface {
	Generate(*up.CompileUnit) ([]byte, error)
}

type generateFunc func(*up.CompileUnit) ([]byte, error)

func (f generateFunc) Generate(unit *up.CompileUnit) ([]byte, error) {
	return f(unit)
}

type generator struct {
	unit    *up.CompileUnit
	imports map[string]string
	content sections
}

type sections struct {
	comments bytes.Buffer
	imports  bytes.Buffer
	code     bytes.Buffer
}

func (s *sections) reset() {
	(&s.comments).Reset()
	(&s.imports).Reset()
	(&s.code).Reset()
}

func New() *generator {
	g := &generator{}
	g.reset()
	return g
}

const (
	methodReceiverName = "up"
	writerVarName      = "__pushup_w"
	pushupApi          = "github.com/adhocteam/pushup"
	pushupModulePath   = "github.com/adhocteam/pushup"
)

func (g *generator) reset() {
	g.content.reset()
	g.imports = make(map[string]string)
}

func (g *generator) Generate(unit *up.CompileUnit) ([]byte, error) {
	g.unit = unit
	g.reset()

	g.addComment("Code generated by Pushup; DO NOT EDIT")
	g.addComment("Version: " + version.Version())

	g.generateResponder(unit.TypeName, unit.Handler, g.generate)

	type route struct {
		path     string
		typeName string
	}
	var routes []route

	routes = append(routes, route{path: unit.Route, typeName: unit.TypeName})

	for _, partial := range g.unit.Partials {
		g.generateResponder(partial.TypeName, unit.Handler, func() {
			// FIXME(paulsmith): need to generate code for everything but emitting
			// top-level page values to the output
			g.genNodePartial(g.unit.Nodes, partial)
		})
		routes = append(routes, route{path: partial.Route, typeName: partial.TypeName})
	}

	// Register routes
	if g.unit.File.Kind == up.Page {
		g.println("")
		g.println("func init() {")
		g.addImport(pushupModulePath+"/route", "")
		for _, route := range routes {
			g.printf("route.Register(\"%s\", new(%s))\n", route.path, route.typeName)
		}
		g.println("}")
	}

	code, err := g.bytes()
	if err != nil {
		return nil, fmt.Errorf("getting generated code bytes: %w", err)
	}

	code, err = format.Source(code)
	if err != nil {
		return nil, fmt.Errorf("formatting generated Go code: %w", err)
	}

	return code, nil
}

func (g *generator) generateResponder(typename string, handler *ast.NodeGoCode, codegenFn func()) {
	g.addImport(pushupApi, "api")
	g.addImport("net/http", "")

	g.printf("type %s struct {\n", typename)
	g.println("}")
	g.println("")

	g.printf("type %s_usercontext struct {\n", typename)
	g.println(" request *http.Request")
	g.println(" writer http.ResponseWriter")
	g.println(" params map[string]any")
	g.println(" children func(api.UserContext)")
	g.println("}")
	g.println("")

	g.printf("func (ctx *%s_usercontext) Request() *http.Request { return ctx.request }\n", typename)
	g.println("")
	g.printf("func (ctx *%s_usercontext) Writer() http.ResponseWriter { return ctx.writer }\n", typename)
	g.println("")
	g.printf("func (ctx *%s_usercontext) Params() map[string]any { return ctx.params }\n", typename)
	g.println("")
	g.printf("func (ctx *%s_usercontext) Children() func(api.UserContext) { return ctx.children }\n", typename)
	g.println("")

	g.printf("func user_%s(ctx api.UserContext) error {\n", typename)
	if handler != nil {
		srcLineNo := g.lineNo(handler.Pos())
		lines := strings.Split(handler.Code, "\n")
		for _, line := range lines {
			g.emitLineDirective(srcLineNo)
			g.println(line)
			srcLineNo++
		}
	}
	codegenFn()
	g.println("ctx.Writer().(http.Flusher).Flush()")
	g.println("return nil")
	g.println("}")
	g.println("")

	if g.unit.File.Kind == up.Page {
		g.printf("func (%s *%s) Respond(w http.ResponseWriter, req *http.Request) error {\n", methodReceiverName, typename)
		g.println("w.Header().Set(\"Content-Type\", \"text/html\")")
	} else if g.unit.File.Kind == up.Component {
		g.printf("func (%s *%s) Respond(w http.ResponseWriter, req *http.Request, params map[string]any, children func(api.UserContext)) error {\n", methodReceiverName, typename)
	} else {
		panic("unexpected file kind")
	}

	g.printf("ctx := new(%s_usercontext)\n", typename)
	g.println("ctx.request = req")
	g.println("ctx.writer = api.NewResponseWriter(w)")
	if g.unit.File.Kind == up.Component {
		g.println("ctx.params = params")
		g.println("ctx.children = children")
	}
	g.printf("err := user_%s(ctx)\n", typename)
	g.println("return err")
	g.println("}") // end Respond() method
}

func (g *generator) generate() {
	ops := g.collectOutputOps(g.unit.Nodes)
	g.generateFromOps(ops)
}

func (g *generator) generateFromOps(ops []outputOp) {
	if len(ops) == 0 {
		return
	}
	prev := ops[0]
	for _, op := range ops {
		if !op.noNl && !prev.noNl {
			g.emitLineDirective(g.lineNo(op.span))
		}

		switch op.kind {
		case opStatic:
			g.addImport("io", "")
			g.printf("io.WriteString(ctx.Writer(), %s)\n", strconv.Quote(op.content))
		case opDynamic:
			g.addImport(pushupApi, "api")
			g.printf("api.PrintEscaped(ctx.Writer(), %s)\n", op.content)
		case opFlush:
			g.println("ctx.Writer().(http.Flusher).Flush()")
			continue
		case opGoCode:
			if op.noNl {
				g.printf("%s", op.content)
			} else {
				g.println(op.content)
			}
		case opControlStart:
			g.printf("%s {\n", op.content)
		case opControlElse:
			g.println("} else {")
		case opControlEnd:
			g.println("}")
		default:
			panic("unknown output op kind")
		}
		prev = op
	}
}

func (g *generator) collectOutputOps(node ast.Node) []outputOp {
	collector := new(outputCollector)
	g.gatherOutputOps(node, collector)
	return collector.optimize()
}

func (g *generator) gatherOutputOps(node ast.Node, collector *outputCollector) {
	switch n := node.(type) {
	case *ast.NodeLiteral:
		collector.add(outputOp{
			kind:    opStatic,
			content: n.Text,
			span:    n.Span,
		})

	case *ast.NodeElement:
		if _, ok := g.unit.ComponentCallSites[n]; ok {
			g.outputComponentCallSite(n, collector)
			break
		}

		if g.unit.File.Kind == up.Component && n.Tag.Name == "children" {
			collector.add(outputOp{
				kind:    opGoCode,
				content: fmt.Sprintf("if ctx.Children() != nil { ctx.Children()(ctx) }"),
			})
			collector.add(outputOp{kind: opFlush})
			break
		}

		collector.add(outputOp{
			kind:    opStatic,
			content: n.Tag.Start(),
			span:    n.Span,
		})

		g.gatherOutputOps(n.Children, collector)

		collector.add(outputOp{
			kind:    opStatic,
			content: n.Tag.End(),
			span:    n.Span,
		})

	case *ast.NodeGoStrExpr:
		collector.add(outputOp{
			kind:    opDynamic,
			content: n.Expr,
			span:    n.Span,
		})

	case *ast.NodeParam:
		if !n.Use {
			panic(fmt.Sprintf("syntax invariant violated: ^param keyword in non-use context"))
		}
		g.addImport(pushupApi, "api")
		collector.add(outputOp{
			kind:    opDynamic,
			content: fmt.Sprintf("api.Param(%s, ctx.Request(), ctx.Params())", strconv.Quote(n.Decl.Ident)),
			span:    n.Span,
		})

	case *ast.NodeIf:
		collector.add(outputOp{kind: opFlush})
		collector.add(outputOp{
			kind:    opControlStart,
			content: "if " + n.Cond.Expr,
			span:    n.Pos(),
		})
		g.gatherOutputOps(n.Then, collector)
		if n.Alt != nil {
			collector.add(outputOp{
				kind: opControlElse,
				span: n.Alt.Pos(),
			})
			g.gatherOutputOps(n.Alt, collector)
		}
		collector.add(outputOp{
			kind: opControlEnd,
			span: n.Then.Pos(), // FIXME??
		})
		collector.add(outputOp{kind: opFlush})

	case *ast.NodeFor:
		collector.add(outputOp{kind: opFlush})
		collector.add(outputOp{
			kind:    opControlStart,
			content: "for " + n.Clause.Code,
			span:    n.Pos(),
		})
		g.gatherOutputOps(n.Block, collector)
		collector.add(outputOp{
			kind: opControlEnd,
			span: n.Block.Pos(), // FIXME??
		})
		collector.add(outputOp{kind: opFlush})

	case *ast.NodeList:
		for child := range n.All() {
			g.gatherOutputOps(child, collector)
		}

	case *ast.NodeGoCode:
		if n.Context == ast.InlineGoCode {
			collector.add(outputOp{kind: opFlush})
			collector.add(outputOp{
				kind:    opGoCode,
				content: n.Code,
				span:    n.Span,
			})
			collector.add(outputOp{kind: opFlush})
		}

	case *ast.NodePartial:
		g.gatherOutputOps(n.Block, collector)

	default:
		panic(fmt.Sprintf("unexpected node type: %T %v", n, n))
	}
}

func (g *generator) outputComponentCallSite(node *ast.NodeElement, collector *outputCollector) {
	tag := node.Tag
	collector.add(outputOp{
		kind:    opGoCode,
		content: fmt.Sprintf("(&%s{}).Respond(ctx.Writer(), ctx.Request(), map[string]any{", tag.Name),
		// span: ??? // FIXME
	})
	// TODO: could match function arity (and types?? prob not) to component
	for _, attr := range tag.Attrs {
		for i, node := range attr.NameNodes {
			switch node := node.(type) {
			case *ast.NodeLiteral:
				collector.add(outputOp{
					kind:    opGoCode,
					content: strconv.Quote(node.Text),
					span:    node.Pos(),
					noNl:    true,
				})
			case *ast.NodeGoStrExpr:
				g.addImport("fmt", "")
				collector.add(outputOp{
					kind:    opGoCode,
					content: fmt.Sprintf("fmt.Sprint(%s)", node.Expr),
					span:    node.Pos(),
					noNl:    true,
				})
			default:
				panic(fmt.Sprintf("expected node literal or Go string expr, got: %T", node))
			}
			if i < len(attr.NameNodes)-1 {
				collector.add(outputOp{
					kind:    opGoCode,
					content: "+",
					noNl:    true,
				})
			}
		}

		collector.add(outputOp{
			kind:    opGoCode,
			content: ": ",
			noNl:    true,
		})

		for i, node := range attr.ValueNodes {
			switch node := node.(type) {
			case *ast.NodeLiteral:
				collector.add(outputOp{
					kind:    opGoCode,
					content: strconv.Quote(node.Text),
					span:    node.Pos(),
					noNl:    true,
				})
			case *ast.NodeGoStrExpr:
				g.addImport("fmt", "")
				collector.add(outputOp{
					kind:    opGoCode,
					content: fmt.Sprintf("fmt.Sprint(%s)", node.Expr),
					span:    node.Pos(),
					noNl:    true,
				})
			default:
				panic(fmt.Sprintf("expected node literal or Go string expr, got: %T", node))
			}
			if i < len(attr.NameNodes)-1 {
				collector.add(outputOp{
					kind:    opGoCode,
					content: "+",
					noNl:    true,
				})
			}
		}

		collector.add(outputOp{
			kind:    opGoCode,
			content: ",",
		})
	}

	collector.add(outputOp{
		kind:    opGoCode,
		content: "},",
	})

	if node.Children.Len() > 0 {
		collector.add(outputOp{
			kind: opGoCode,
			// TODO: consider writer type
			content: fmt.Sprintf("func(ctx api.UserContext) {"),
		})

		g.gatherOutputOps(node.Children, collector)

		collector.add(outputOp{
			kind:    opGoCode,
			content: "},",
		})
	} else {
		collector.add(outputOp{
			kind:    opGoCode,
			content: "nil,",
		})
	}

	collector.add(outputOp{
		kind:    opGoCode,
		content: ")",
	})
}

func (g *generator) nodeLineNo(e ast.Node) {
	g.emitLineDirective(g.lineNo(e.Pos()))
}

// NOTE(paulsmith): per DOM spec, "In tree order is preorder, depth-first traversal of a tree."

func (g *generator) genNodePartial(n ast.Node, p *up.Partial) {
	var f ast.Inspector
	var state int
	const (
		stateStart int = iota
		stateInPartialScope
	)
	state = stateStart
	nodes := &ast.NodeList{}

	f = func(n ast.Node) bool {
		if n != nil {
			switch n := n.(type) {
			case *ast.NodePartial:
				if n == p.Node {
					state = stateInPartialScope
				}
				f(n.Block)
				state = stateStart
				return false
			case *ast.NodeList:
				if state == stateInPartialScope {
					nodes.AppendFromList(n)
				} else {
					for node := range n.All() {
						f(node)
					}
				}
			case *ast.NodeLiteral:
				if state == stateInPartialScope {
					g.addImport("io", "")
					g.nodeLineNo(n)
					g.printf("io.WriteString(%s, %s)\n", writerVarName, strconv.Quote(n.Text))
				}
			default:
				if state == stateInPartialScope {
					nodes.Append(n)
				}
			}
		}

		return false
	}

	ast.Inspect(n, f)

	ops := g.collectOutputOps(nodes)
	g.generateFromOps(ops)
}

func (g *generator) addComment(comment string) {
	fmt.Fprintln(&g.content.comments, "//", comment)
}

func (g *generator) addImport(path, pkgName string) {
	g.imports[path] = pkgName
}

func (g *generator) println(code string) {
	fmt.Fprintln(&g.content.code, code)
}

func (g *generator) printf(format string, a ...any) {
	fmt.Fprintf(&g.content.code, format, a...)
}

func (g *generator) lineNo(s source.Span) int {
	return lineCount(g.unit.File.Content[:s.Start+1])
}

func (g *generator) emitLineDirective(n int) {
	fmt.Fprintf(&g.content.code, "//line %s:%d\n", g.unit.File.Path, n)
}

func (g *generator) bytes() ([]byte, error) {
	pkgDecl := strings.NewReader("package " + g.unit.Package + "\n")

	for _, decl := range g.unit.Imports {
		g.imports[decl.Path] = decl.PkgName
	}

	if len(g.imports) > 0 {
		fmt.Fprintln(&g.content.imports, "import (")
		for path, pkgName := range g.imports {
			if pkgName == "" {
				fmt.Fprintf(&g.content.imports, "\t%q\n", path)
			} else {
				fmt.Fprintf(&g.content.imports, "\t%s %q\n", pkgName, path)
			}
		}
		fmt.Fprintln(&g.content.imports, ")")
	}

	bufs := []io.Reader{
		&g.content.comments,
		pkgDecl,
		&g.content.imports,
		&g.content.code,
	}
	return io.ReadAll(io.MultiReader(bufs...))
}

var nl = []byte{'\n'}

func lineCount(s []byte) int {
	return bytes.Count(s, nl) + 1
}
