package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"strconv"
	"strings"

	"github.com/adhocteam/pushup/internal/ast"
	"github.com/adhocteam/pushup/internal/source"
	"github.com/adhocteam/pushup/internal/up"
	"github.com/adhocteam/pushup/internal/version"
)

type Generator interface {
	Generate(*up.CompileUnit) ([]byte, error)
}

type generateFunc func(*up.CompileUnit) ([]byte, error)

func (f generateFunc) Generate(unit *up.CompileUnit) ([]byte, error) {
	return f(unit)
}

type generator struct {
	unit    *up.CompileUnit
	imports map[string]string
	content sections
}

type sections struct {
	comments bytes.Buffer
	imports  bytes.Buffer
	code     bytes.Buffer
}

func (s *sections) reset() {
	(&s.comments).Reset()
	(&s.imports).Reset()
	(&s.code).Reset()
}

func New() *generator {
	g := &generator{}
	g.reset()
	return g
}

const (
	writerVarName    = "__pushup_w"
	pushupApi        = "github.com/adhocteam/pushup"
	pushupModulePath = "github.com/adhocteam/pushup"
)

func (g *generator) reset() {
	g.content.reset()
	g.imports = make(map[string]string)
}

func (g *generator) Generate(unit *up.CompileUnit) ([]byte, error) {
	g.unit = unit
	g.reset()

	g.addComment("Code generated by Pushup; DO NOT EDIT")
	g.addComment("Version: " + version.Version())

	g.generateResponder(unit.TypeName, g.generate)

	type route struct {
		pattern   string
		isPartial bool
	}
	var routes []route
	routes = append(routes, route{pattern: unit.Route})
	for _, partial := range unit.Partials {
		routes = append(routes, route{pattern: partial.Route, isPartial: true})
	}

	// Register routes and map patterns to partials
	if g.unit.File.Kind == up.Page {
		g.println("")
		g.println("func init() {")
		g.addImport(pushupModulePath+"/route", "")
		for _, route := range routes {
			role := "route.RolePage"
			if route.isPartial {
				role = "route.RolePartial"
			}
			g.printf("route.Register(\"%s\", new(%s), %v)\n", route.pattern, unit.TypeName, role)
		}
		g.println("}")
		g.println("")
	}

	code, err := g.bytes()
	if err != nil {
		return nil, fmt.Errorf("getting generated code bytes: %w", err)
	}

	code, err = format.Source(code)
	if err != nil {
		return nil, fmt.Errorf("formatting generated Go code: %w", err)
	}

	return code, nil
}

func (g *generator) generateResponder(typename string, codegenFn func()) {
	g.addImport(pushupApi, "api")
	g.addImport("net/http", "")

	g.printf("type %s struct {\n", typename)
	g.println("}")
	g.println("")

	g.printf("type %s_pushupcontext struct {\n", typename)
	g.println(" request *http.Request")
	g.println(" writer http.ResponseWriter")
	g.println(" params map[string]any")
	g.println(" children func(api.PushupContext)")
	g.println("}")
	g.println("")

	g.printf("func (ctx *%s_pushupcontext) Request() *http.Request { return ctx.request }\n", typename)
	g.println("")
	g.printf("func (ctx *%s_pushupcontext) Writer() http.ResponseWriter { return ctx.writer }\n", typename)
	g.println("")
	g.printf("func (ctx *%s_pushupcontext) Params() map[string]any { return ctx.params }\n", typename)
	g.println("")
	g.printf("func (ctx *%s_pushupcontext) Children() func(api.PushupContext) { return ctx.children }\n", typename)
	g.println("")

	g.printf("func user_%s(ctx api.PushupContext) error {\n", typename)
	if g.unit.File.Kind == up.Page {
		g.println("if route.IsPartial(ctx.Request(), \"\") {")
		g.println("  ctx.Writer().(*api.ResponseWriter).SetDiscard()")
		g.println("}")
	}
	codegenFn()
	g.println("ctx.Writer().(http.Flusher).Flush()")
	g.println("return nil")
	g.println("}")
	g.println("")

	if g.unit.File.Kind == up.Page {
		g.printf("func (up *%s) Respond(w http.ResponseWriter, req *http.Request) error {\n", typename)
		g.println("w.Header().Set(\"Content-Type\", \"text/html; charset=utf-8\")")
	} else if g.unit.File.Kind == up.Component {
		g.printf("func (up *%s) Respond(w http.ResponseWriter, req *http.Request, params map[string]any, children func(api.PushupContext)) error {\n", typename)
	} else {
		panic("unexpected file kind")
	}

	g.printf("ctx := new(%s_pushupcontext)\n", typename)
	g.println("ctx.request = req")
	g.println("ctx.writer = api.NewResponseWriter(w)")
	if g.unit.File.Kind == up.Component {
		g.println("ctx.params = params")
		g.println("ctx.children = children")
	}
	g.printf("err := user_%s(ctx)\n", typename)
	g.println("return err")
	g.println("}") // end Respond() method
}

func (g *generator) generate() {
	ops := g.collectOutputOps(g.unit.Nodes)
	g.generateFromOps(ops)
}

func (g *generator) generateFromOps(ops []outputOp) {
	if len(ops) == 0 {
		return
	}
	prev := ops[0]
	for _, op := range ops {
		if !op.noNl && !prev.noNl {
			g.emitLineDirective(g.lineNo(op.span))
		}

		switch op.kind {
		case opStatic:
			g.addImport("io", "")
			g.printf("io.WriteString(ctx.Writer(), %s)\n", strconv.Quote(op.content))
		case opDynamic:
			g.addImport(pushupApi, "api")
			g.printf("api.PrintEscaped(ctx.Writer(), %s)\n", op.content)
		case opFlush:
			// TODO: flushing output has to be considered carefully
			//g.println("ctx.Writer().(http.Flusher).Flush()")
		case opGoCode:
			if op.noNl {
				g.printf("%s", op.content)
			} else {
				g.println(op.content)
			}
		case opControlStart:
			g.printf("%s {\n", op.content)
		case opControlElse:
			g.println("} else {")
		case opControlEnd:
			g.println("}")
		default:
			panic("unknown output op kind")
		}
		prev = op
	}
}

func (g *generator) collectOutputOps(node ast.Node) []outputOp {
	collector := new(outputCollector)
	g.gatherOutputOps(node, collector)
	return collector.optimize()
}

func (g *generator) gatherOutputOps(node ast.Node, collector *outputCollector) {
	switch n := node.(type) {
	case *ast.NodeLiteral:
		collector.add(outputOp{
			kind:    opStatic,
			content: n.Text,
			span:    n.Span,
		})

	case *ast.NodeElement:
		if _, ok := g.unit.ComponentCallSites[n]; ok {
			g.outputComponentCallSite(n, collector)
			break
		}

		if g.unit.File.Kind == up.Component && n.Tag.Name == "children" {
			collector.add(outputOp{
				kind:    opGoCode,
				content: fmt.Sprintf("if ctx.Children() != nil { ctx.Children()(ctx) }"),
			})
			collector.add(outputOp{kind: opFlush})
			break
		}

		collector.add(outputOp{
			kind:    opStatic,
			content: "<" + n.Tag.Name,
			span:    n.Span,
		})

		if len(n.Tag.Attrs) > 0 {
			collector.add(outputOp{
				kind:    opStatic,
				content: " ",
				span:    n.Span,
			})
		}

		// TODO: the complexity of this could be better organized/encapsulated
		for i, attr := range n.Tag.Attrs {
			var lastSpan source.Span
			for _, nameNode := range attr.NameNodes {
				g.gatherOutputOps(nameNode, collector)
				lastSpan = nameNode.Pos()
			}
			if len(attr.ValueNodes) > 0 {
				collector.add(outputOp{
					kind:    opStatic,
					content: `="`,
					span:    lastSpan,
				})
			}
			for _, valueNode := range attr.ValueNodes {
				g.gatherOutputOps(valueNode, collector)
				lastSpan = valueNode.Pos()
			}
			if len(attr.ValueNodes) > 0 {
				collector.add(outputOp{
					kind:    opStatic,
					content: `"`,
					span:    lastSpan,
				})
			}
			if i < len(n.Tag.Attrs)-1 {
				collector.add(outputOp{
					kind:    opStatic,
					content: " ",
					span:    lastSpan,
				})
			}
		}

		collector.add(outputOp{
			kind:    opStatic,
			content: ">",
			span:    n.Span,
		})

		if n.NeedsClosingTag() {
			g.gatherOutputOps(n.Children, collector)

			collector.add(outputOp{
				kind:    opStatic,
				content: n.Tag.End(),
				span:    n.Span,
			})
		}

	case *ast.NodeGoStrExpr:
		collector.add(outputOp{
			kind:    opDynamic,
			content: n.Expr,
			span:    n.Span,
		})

	case *ast.NodeParam:
		if !n.Use {
			panic(fmt.Sprintf("syntax invariant violated: ^param keyword in non-use context"))
		}
		g.addImport(pushupApi, "api")
		collector.add(outputOp{
			kind:    opDynamic,
			content: fmt.Sprintf("api.Param(%s, ctx.Request(), ctx.Params())", strconv.Quote(n.Decl.Ident)),
			span:    n.Span,
		})

	case *ast.NodeIf:
		collector.add(outputOp{kind: opFlush})
		collector.add(outputOp{
			kind:    opControlStart,
			content: "if " + n.Cond.Expr,
			span:    n.Pos(),
		})
		g.gatherOutputOps(n.Then, collector)
		if n.Alt != nil {
			collector.add(outputOp{
				kind: opControlElse,
				span: n.Alt.Pos(),
			})
			g.gatherOutputOps(n.Alt, collector)
		}
		collector.add(outputOp{
			kind: opControlEnd,
			span: n.Then.Pos(), // FIXME??
		})
		collector.add(outputOp{kind: opFlush})

	case *ast.NodeFor:
		collector.add(outputOp{kind: opFlush})
		collector.add(outputOp{
			kind:    opControlStart,
			content: "for " + n.Clause.Code,
			span:    n.Pos(),
		})
		g.gatherOutputOps(n.Block, collector)
		collector.add(outputOp{
			kind: opControlEnd,
			span: n.Block.Pos(), // FIXME??
		})
		collector.add(outputOp{kind: opFlush})

	case *ast.NodeList:
		for child := range n.All() {
			g.gatherOutputOps(child, collector)
		}

	case *ast.NodeGoCode:
		collector.add(outputOp{kind: opFlush})
		collector.add(outputOp{
			kind:    opGoCode,
			content: n.Code,
			span:    n.Span,
		})
		collector.add(outputOp{kind: opFlush})

	case *ast.NodePartial:
		partial := g.unit.Partials[n]

		collector.add(outputOp{
			kind: opGoCode,
			content: fmt.Sprintf(`if route.IsPartial(ctx.Request(), "%s") {
    ctx.Writer().(*api.ResponseWriter).UnsetDiscard()
}`, partial.Route),
		})
		g.gatherOutputOps(n.Block, collector)
		collector.add(outputOp{
			kind: opGoCode,
			content: fmt.Sprintf(`if route.IsPartial(ctx.Request(), "%s") {
    ctx.Writer().(*api.ResponseWriter).SetDiscard()
}`, partial.Route),
		})

	default:
		panic(fmt.Sprintf("unexpected node type: %T %v", n, n))
	}
}

func (g *generator) outputComponentCallSite(node *ast.NodeElement, collector *outputCollector) {
	tag := node.Tag
	collector.add(outputOp{
		kind:    opGoCode,
		content: fmt.Sprintf("(&%s{}).Respond(ctx.Writer(), ctx.Request(), map[string]any{", tag.Name),
		// span: ??? // FIXME
	})
	// TODO: could match function arity (and types?? prob not) to component
	for _, attr := range tag.Attrs {
		for i, node := range attr.NameNodes {
			switch node := node.(type) {
			case *ast.NodeLiteral:
				collector.add(outputOp{
					kind:    opGoCode,
					content: strconv.Quote(node.Text),
					span:    node.Pos(),
					noNl:    true,
				})
			case *ast.NodeGoStrExpr:
				g.addImport("fmt", "")
				collector.add(outputOp{
					kind:    opGoCode,
					content: fmt.Sprintf("fmt.Sprint(%s)", node.Expr),
					span:    node.Pos(),
					noNl:    true,
				})
			default:
				panic(fmt.Sprintf("expected node literal or Go string expr, got: %T", node))
			}
			if i < len(attr.NameNodes)-1 {
				collector.add(outputOp{
					kind:    opGoCode,
					content: "+",
					noNl:    true,
				})
			}
		}

		collector.add(outputOp{
			kind:    opGoCode,
			content: ": ",
			noNl:    true,
		})

		for i, node := range attr.ValueNodes {
			switch node := node.(type) {
			case *ast.NodeLiteral:
				collector.add(outputOp{
					kind:    opGoCode,
					content: strconv.Quote(node.Text),
					span:    node.Pos(),
					noNl:    true,
				})
			case *ast.NodeGoStrExpr:
				collector.add(outputOp{
					kind:    opGoCode,
					content: node.Expr,
					span:    node.Pos(),
					noNl:    true,
				})
			default:
				panic(fmt.Sprintf("expected node literal or Go string expr, got: %T", node))
			}
			if i < len(attr.NameNodes)-1 {
				collector.add(outputOp{
					kind:    opGoCode,
					content: "+",
					noNl:    true,
				})
			}
		}

		collector.add(outputOp{
			kind:    opGoCode,
			content: ",",
		})
	}

	collector.add(outputOp{
		kind:    opGoCode,
		content: "},",
	})

	if node.Children.Len() > 0 {
		collector.add(outputOp{
			kind: opGoCode,
			// TODO: consider writer type
			content: fmt.Sprintf("func(ctx api.PushupContext) {"),
		})

		g.gatherOutputOps(node.Children, collector)

		collector.add(outputOp{
			kind:    opGoCode,
			content: "},",
		})
	} else {
		collector.add(outputOp{
			kind:    opGoCode,
			content: "nil,",
		})
	}

	collector.add(outputOp{
		kind:    opGoCode,
		content: ")",
	})
}

func (g *generator) nodeLineNo(e ast.Node) {
	g.emitLineDirective(g.lineNo(e.Pos()))
}

func (g *generator) addComment(comment string) {
	fmt.Fprintln(&g.content.comments, "//", comment)
}

func (g *generator) addImport(path, pkgName string) {
	g.imports[path] = pkgName
}

func (g *generator) println(code string) {
	fmt.Fprintln(&g.content.code, code)
}

func (g *generator) printf(format string, a ...any) {
	fmt.Fprintf(&g.content.code, format, a...)
}

func (g *generator) lineNo(s source.Span) int {
	return lineCount(g.unit.File.Content[:s.Start+1])
}

func (g *generator) emitLineDirective(n int) {
	fmt.Fprintf(&g.content.code, "//line %s:%d\n", g.unit.File.Path, n)
}

func (g *generator) bytes() ([]byte, error) {
	pkgDecl := strings.NewReader("package " + g.unit.Package + "\n")

	for _, decl := range g.unit.Imports {
		g.imports[decl.Path] = decl.PkgName
	}

	if len(g.imports) > 0 {
		fmt.Fprintln(&g.content.imports, "import (")
		for path, pkgName := range g.imports {
			if pkgName == "" {
				fmt.Fprintf(&g.content.imports, "\t%q\n", path)
			} else {
				fmt.Fprintf(&g.content.imports, "\t%s %q\n", pkgName, path)
			}
		}
		fmt.Fprintln(&g.content.imports, ")")
	}

	bufs := []io.Reader{
		&g.content.comments,
		pkgDecl,
		&g.content.imports,
		&g.content.code,
	}
	return io.ReadAll(io.MultiReader(bufs...))
}

var nl = []byte{'\n'}

func lineCount(s []byte) int {
	return bytes.Count(s, nl) + 1
}
